/hardening/image-builder: prevent errors on in-development RHEL versions
Try to prevent the following error (usually happens on new RHEL versions
which are still in development):
```
ERROR: BlueprintsError: contest_blueprint: GetDistro - unknown distribution rhel-X.Y
```
which is caused by the absence of `rhel-X.Y.json` file in
`/usr/share/osbuild-composer/repositories`;
if `/usr/share/osbuild-composer/repositories/rhel-X.Y.json` does not exist,
we try to create it by copying `rhel-X.json` if it exists.