fix proc / self.proc typo in lib.podman
This was incorrectly matching another 'proc' from the try: block,
which was a subprocess.run() and not subproces.Popen(), meaning
'proc' was a CompletedProcess and not a Popen object, leading to

AttributeError: 'CompletedProcess' object has no attribute 'terminate'

The obvious intention was to shut down the background Popen process,
so do that.

Signed-off-by: Jiri Jaburek <comps@nomail.dom>